### ISSUE TITLE
User Can See Prompt for Current Letter 

### ISSUE THREAD

**Issue by Kiptong** [Kiptong/typing-test#3]
# Motivation 
Allows user to see which letter they are being asked to type for the test. 

# Implementation 
- [x] Link index.html with main.js
- [x] Add "id" selectors to the proper html tags for javascript functionalty  
- [x] Write javascript to select a individual char within the typing-test string 
- [x] Write a javascript that turns the selected char bold

**Comment by victormejia** [comment]
@Kiptong you actually assign issues to the person working on it, in this case yourself.

**Comment by Kiptong** [comment]
Thanks!
